INSERT OR IGNORE INTO settings (key, value) VALUES
  ('ui.font_size', '13'),
  ('ui.accent', 'rose'),
  ('ui.nav_shape', 'rounded'),
  ('alert.low_stock', '1'),
  ('alert.expiry', '1'),
  ('alert.batch_expiry', '1'),
  ('alert.sales', '1'),
  ('alert.backup', '1'),
  ('printer.a4', ''),
  ('printer.cash_drawer', '0'),
  ('printer.drawer_on_sale', '0'),
  ('scanner.enabled', '1'),
  ('scanner.suffix', 'Enter'),
  ('invoice.style', 'receipt'),
  ('invoice.paper', '80mm'),
  ('invoice.show_logo', '1'),
  ('invoice.show_tax', '1'),
  ('invoice.show_barcode', '0'),
  ('store.email', ''),
  ('store.logo_path', ''),
  ('store.whatsapp', ''),
  ('store.website', ''),
  ('barcode.auto', '0'),
  ('barcode.prefix', ''),
  ('batch.require_lot', '1'),
  ('batch.require_expiry', '1'),
  ('cosmetics.colors', 'أحمر، وردي، بيج، ذهبي'),
  ('cosmetics.sizes', '15ml، 30ml، 50ml، 100ml'),
  ('cosmetics.shades', 'Fair، Light، Medium، Tan'),
  ('cosmetics.types', 'كريم، سيروم، ماسكارا، أحمر شفاه، عطر');
